### ISSUE TITLE
金琦

### ISSUE THREAD

**Issue by jin-qi123** [QSCTech/2023-autumn-round-two#11]
因为时间分配不够，我选择放弃二面。目前只做了第6题，但这次做题让我接触到了很多新的东西，希望未来更好的我能有机会加入求是潮   https://www.figma.com/file/DZPnNFYKWPY6q8fXd8NytW/Untitled?type=design&node-id=0%3A1&mode=design&t=wdXxdUHi19Qy8EFv-1

**Comment by Winfred666** [comment]
感谢您的参与！宇宙很大，生活更大，期待与您未来相见！
