### ISSUE TITLE
徐敏睿

### ISSUE THREAD

**Issue by allfadeaway** [QSCTech/2023-autumn-round-two#14]
我选择题目6和题目2进行作答
这是我题目2的[仓库](https://github.com/allfadeaway/QSCTech)
这是我题目6的[链接](https://www.figma.com/file/hsyel4vvGpm4PYt3wouYZ9/Untitled?type=design&node-id=0-1&mode=design&t=lytKtwxApaTNc0uc-0)

**Comment by Winfred666** [comment]
感谢您的付出~
