### ISSUE TITLE
胡晨歌

### ISSUE THREAD

**Issue by hello-world112233** [QSCTech/2023-autumn-round-two#16]
common   https://www.figma.com/file/Pm8hMcfUFTHFfIYAx2JmSS/Untitled?type=design&node-id=0-1&mode=design&t=ooGU72wuvUvSZvFN-0

**Comment by hello-world112233** [comment]
我本来想做magic clock的，但是不知道为什么在配置node.js的时候cnpm下载后一直找不到？

**Comment by Winfred666** [comment]
本来在使用nodejs过程中换镜像、开管理员权限是提示的一部分，但因为要求删掉不少（捂脸哭）
但感谢您的参与，期待与您二面相见！

**Comment by hello-world112233** [comment]
我已经找到方法了！能不能等等我！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月29日(星期五) 晚上7:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QSCTech/2023-autumn-round-two] 胡晨歌 (Issue #16)





 
本来在使用nodejs过程中换镜像、开管理员权限是提示的一部分，但因为要求删掉不少（捂脸哭）
 但感谢您的参与，期待与您二面相见！

**Comment by hello-world112233** [comment]
这个是不是会扣分（哭），我真的是纯小白，对不起，选了31个学分，周一到周四课很多，很晚才开始学习，如果我后期搞定了还可以提交吗？非常感谢您对我的及时回复和帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QSCTech/2023-autumn-round-two"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月29日(星期五) 晚上7:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QSCTech/2023-autumn-round-two] 胡晨歌 (Issue #16)





 
本来在使用nodejs过程中换镜像、开管理员权限是提示的一部分，但因为要求删掉不少（捂脸哭）
 但感谢您的参与，期待与您二面相见！

**Comment by Winfred666** [comment]
当然可以继续学习和改进，我们更看重的是热情和付出。希望您可以平衡各项时间，以充足的精力和热情投入之后的开发！

**Comment by hello-world112233** [comment]
<img width="811" alt="image" src="https://github.com/QSCTech/2023-autumn-round-two/assets/146430616/9cf32345-1b32-487f-9050-a6dc89da4508">
我已经尝试了以管理员方式打开cmd，以及换了taobao的镜像，但是还是找不到
<img width="823" alt="image" src="https://github.com/QSCTech/2023-autumn-round-two/assets/146430616/2159b64d-20fe-43fe-8db8-9a6152f0df17">
<img width="447" alt="image" src="https://github.com/QSCTech/2023-autumn-round-two/assets/146430616/439bb220-611f-476f-a168-b7b5c8e41a47">

**Comment by Winfred666** [comment]
看npm的WARN提示，好像是拼错镜像源了hh，不用着急，多摸索，你可以的
