### ISSUE TITLE
谭昭阳

### ISSUE THREAD

**Issue by x6eull** [QSCTech/2023-autumn-round-two#2]
我选择第4题和第6题作答
## 第4题
部署url：https://objflux.com/tool/of/markdown
核心代码仓库：https://github.com/x6eull/qsc-r2-markdown
上述仓库为私有仓库，已邀请Gingo
## 第6题
figma链接：https://www.figma.com/file/eVRMjbTxzjTqgRPwnNxuuM/qsc-r2-common?type=design

**Comment by memset0** [comment]
怎么只给Gingo看，可恶！

**Comment by zjuatri** [comment]
怎么只给Gingo看，可恶！

**Comment by x6eull** [comment]
相应仓库已设为Public，欢迎交流学习
