### ISSUE TITLE
李宇怀

### ISSUE THREAD

**Issue by Lin-future** [QSCTech/2023-autumn-round-two#23]
我选择了题目1和题目6进行作答
这是我题目1的[仓库](https://github.com/Lin-future/naive-server.git)
这是我题目6的[连接](https://www.figma.com/file/qMdnwwxCvz8lLSig20Gy7c/commom?type=design&node-id=0%3A1&mode=design&t=jt3QWqW0j43mFMd2-1)

**Comment by Winfred666** [comment]
感谢您的参与和付出！
