### ISSUE TITLE
钱满亮

### ISSUE THREAD

**Issue by AuroraOlian** [QSCTech/2023-autumn-round-two#28]
https://github.com/kyrieliang/zjuqsc

**Comment by AuroraOlian** [comment]
naive server and common

**Comment by Cillo-x** [comment]
无法访问到您的仓库
请检查是什么问题

**Comment by AuroraOlian** [comment]
好的好的&nbsp;


Flechazo
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月29日(星期五) 晚上8:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [QSCTech/2023-autumn-round-two] 钱满亮 (Issue #28)





 
无法访问到您的仓库
 请检查是什么问题
